"""Add updated_at to Note table

Revision ID: 020f74466067
Revises: d127ed2c8e94
Create Date: 2026-02-07 03:03:36.519042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '020f74466067'
down_revision: Union[str, None] = 'd127ed2c8e94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Step 1: Add column as nullable
    op.add_column('note', sa.Column('updated_at', sa.DateTime(), nullable=True))
    
    # Step 2: Set default value for existing rows (use created_at value)
    op.execute("UPDATE note SET updated_at = created_at WHERE updated_at IS NULL")
    
    # Step 3: Make it NOT NULL
    op.alter_column('note', 'updated_at', nullable=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('note', 'updated_at')
    # ### end Alembic commands ###
